title: Andy Chang # your name (or website title) here
logo: "/images/UQ_BEL_27th_Sept_2022_Yen-Ti_Chang_003.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm deeply passionate about Data Science and committed to 
  achieving excellence in Data Analytics.  <br><br>
  <a href="https://www.linkedin.com/in/andy-yen-ti-chang/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
